import pandas as pd
from sentence_transformers import SentenceTransformer
import chromadb
import os
import ollama
import json
from datetime import datetime
import csv
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class TeaDiseaseRAG:
    def __init__(self, excel_path, db_path, embedding_model='BAAI/bge-small-en-v1.5'):
        self.excel_path = excel_path
        self.db_path = db_path
        self.embedding_model_name = embedding_model
        
        # Initialize resources
        self.embedder = SentenceTransformer(self.embedding_model_name)
        self.client = chromadb.PersistentClient(path=self.db_path)
        self.collection = self.client.get_or_create_collection(name="treatments_data")
        
        # Auto-ingest if empty
        if self.collection.count() == 0:
            self.ingest_data()
        else:
            logging.info(f"Database loaded with {self.collection.count()} entries.")

    """
        Loads the tea disease dataset and populates the vector database.
        
        Process:
        1. Reads the Excel file located at 'self.excel_path'.
        2. Loops through every row to extract Disease, Severity, Symptoms, and Treatment.
        3. Creates a 'text_for_embedding' string for each row (this is what the AI actually 'reads').
        4. Generates vector embeddings (lists of numbers) for that text using the SentenceTransformer model.
        5. Saves everything (text, metadata, and embeddings) into ChromaDB so it can be searched later.
    """
    def ingest_data(self):
        #Reads Excel and rebuilds the ChromaDB collection.
        if not os.path.exists(self.excel_path):
            logging.error(f"Excel file not found at {self.excel_path}")
            return

        logging.info("Reading Excel file and generating embeddings...")
        df = pd.read_excel(self.excel_path)
        
        # Find treatment column dynamically
        treatment_col = next((col for col in df.columns if "treatment" in str(col).lower()), None)
        if not treatment_col:
            logging.error("No 'treatment' column found in Excel.")
            return

        documents = []
        metadatas = []
        ids = []

        for index, row in df.iterrows():
            if row.isna().all(): continue

            disease = str(row.get("Disease", "Unknown"))
            severity = str(row.get("Severity", "Unknown")).strip()
            symptoms = str(row.get("Detailed Symptoms", "")).strip()
            treatment = str(row.get(treatment_col, "")).strip()

            # Create a rich text representation for the vector search
            # We focus on symptoms and disease name for the semantic search
            text_for_embedding = (
                f"Disease: {disease}. "
                f"Symptoms include: {symptoms}. "
                f"Recommended treatment: {treatment}."
            )

            documents.append(text_for_embedding)
            
            # Store structured data in metadata for filtering later
            metadatas.append({
                "disease": disease,
                "severity": severity.capitalize(), # Normalize casing
                "symptoms": symptoms,
                "treatments": treatment
            })
            
            # Create unique ID
            clean_id = f"{disease}_{severity}".lower().replace(" ", "_")
            ids.append(clean_id)

        # Batch add to ChromaDB
        if documents:
            self.collection.add(
                documents=documents,
                embeddings=self.embedder.encode(documents).tolist(),
                metadatas=metadatas,
                ids=ids
            )
            logging.info(f"Successfully ingested {len(documents)} records.")


    #params=disease name, severity level, location
    """
        Retrieves the most relevant data and generates an AI response.
        Process:
        1. Converts the user's query (disease + severity) into a vector embedding.
        2. Searches ChromaDB for the best match, filtering specifically for the requested severity (Low/Medium/High).
        3. Extracts the specific symptoms and treatments found in the database.
        4. Sends this factual data to the LLM (Ollama) with a prompt to act as an expert agronomist.
        5. Returns the final, user-friendly advice generated by the AI.
    """
    def get_recommendation(self, disease_name, severity_level, location="Sri Lanka"):
        """Retrieves recommendation using Vector Search + Metadata Filtering."""
        
        query = f"{disease_name} symptoms and treatment"
        query_embedding = self.embedder.encode(query).tolist()
        severity_cap = severity_level.capitalize()

        logging.info(f"Querying for: {disease_name} ({severity_cap})")

        # 1. Search with Metadata Filter (Strict Severity Match)
        results = self.collection.query(
            query_embeddings=[query_embedding],
            n_results=1,
            where={"severity": severity_cap}, # Strict filtering
            include=["metadatas", "distances"]
        )

        # 2. Fallback: If no exact severity match, relax the filter
        if not results['ids'] or not results['ids'][0]:
            logging.warning(f"No match for severity '{severity_cap}'. Searching broadly.")
            results = self.collection.query(
                query_embeddings=[query_embedding],
                n_results=1,
                include=["metadatas", "distances"]
            )

        if not results['ids'] or not results['ids'][0]:
            return {"status": "error", "message": "No matching data found."}

        # Extract best match
        match = results['metadatas'][0][0]
        confidence = round((1 - results['distances'][0][0]) * 100, 1)

        # Generate LLM Response
        llm_prompt = f"""
        You are an expert agricultural assistant for tea farmers in {location}.
        Based ONLY on the following data, provide a treatment plan.
        
        Data:
        - Disease: {match['disease']}
        - Severity: {match['severity']}
        - Symptoms: {match['symptoms']}
        - Treatments: {match['treatments']}
        
        Format your response:
        1. Confirm the disease and severity.
        2. Bullet points for treatments.
        3. A brief safety warning.
        Keep it under 150 words.
        """

        try:
            ollama_response = ollama.chat(model='llama3.1:8b', messages=[
                {'role': 'user', 'content': llm_prompt}
            ])
            final_response = ollama_response['message']['content']
        except Exception as e:
            final_response = f"Error generating AI response: {str(e)}"

        # Log and Return
        self.log_request(query, location, match['disease'], confidence, final_response)
        
        return {
            "status": "success",
            "matched_disease": match['disease'],
            "matched_severity": match['severity'],
            "llm_response": final_response,
            "confidence": confidence
        }



    #params=>query, location, disease, confidence, response
    """
        Logs the query and response to a CSV file.
    """
    def log_request(self, query, location, disease, confidence, response):
        file_exists = os.path.isfile("rag_log.csv")
        with open("rag_log.csv", "a", newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            if not file_exists:
                writer.writerow(["Timestamp", "Query", "Location", "Disease", "Confidence", "Response"])
            writer.writerow([datetime.now(), query, location, disease, confidence, response])


#when you are creating new object of TeaDiseaseRAG you must pass 2 parameters
#1. excel_path :- Where the Excel file is located
#2. db_path :- Where the ChromaDB database is located
#3. embedding_model (optional) :- The embedding model to use (default is 'BAAI/bge-small-en-v1.5')
#rag_system = TeaDiseaseRAG(excel_path="./data_folder/treatments_data_v2.xlsx",db_path="chroma_DB")

#use get_recommendation method to get the recommendation



if __name__ == "__main__":
    # Initialize system once
    rag_system = TeaDiseaseRAG(excel_path="./data_folder/treatments_data_v2.xlsx",db_path="chroma_DB")

    # Run a query
    result = rag_system.get_recommendation(disease_name="Blister Blight", severity_level="Low", location="Hatton")
    
    print("\n--- AI Response ---")
    print(result.get('llm_response', result.get('message')))